dilshod/xlsx2csv

xlsx2csv.py

This issue caused import problems to one of my XLSB -> XLSX files (converted via LibreOffice).

If parsing the "dimension" attribute, ref seems to be optional, so skip if not matched.

---

xlsx2csv.py

When you initialize the class without "**options", not all the default values for self.options are assigned

Updated default params values

---

xlsx2csv.py

This will make sure to use only the decimal place and not the whole number when converting time formats.
* example
* before 08:00:00 = 1900-01-01 08:00:00 = **1.33** = 32:00:00
* after 08:00:00 = 1900-01-01 08:00:00 = **0.33** = 8:00:00
I probably could provide an example xlsx where this occured.

Format type time is using modulo 1

---

xlsx2csv.py

When you use a date format with `AM/PM`, the result is `a%m/p%m`, because the script replaces the occurrences of `m` with `%m` and then searches for `am/pm`.
Also, when `AM/PM` is used, the hour must be formatted in 12hs with `%I`

Fixed AM/PM error

---

xlsx2csv.py

I want to use `xlsx2csv` in UNIX pipeline.
However `xlsx2csv` dump traceback when pipe is closed.
```
$ xlsx2csv | head -1
XXXX,XXX,XXXX
Traceback (most recent call last):
File "/usr/local/bin/xlsx2csv", line 867, in <module>
xlsx2csv.convert(outfile, sheetid)
File "/usr/local/bin/xlsx2csv", line 182, in convert
self._convert(sheetid, outfile)
File "/usr/local/bin/xlsx2csv", line 251, in _convert
sheet.to_csv(writer)
File "/usr/local/bin/xlsx2csv", line 572, in to_csv
self.parser.ParseFile(self.filehandle)
File "/usr/local/bin/xlsx2csv", line 721, in handleEndElement
self.writer.writerow(d)
IOError: [Errno 32] Broken pipe
```
This PR stop the traceback and also stop a traceback on `KeyboardInterrupt`.

Handle SIGPIPE and SIGINT with default handler

---

xlsx2csv.py

such as 'ff' or 'x07' for form feed, which is the default
sheet separator used by the utility xls2csv.

Added the ability to specify an alternative sheetdelimiter

---

xlsx2csv.py

Only outputs line columns that have an entry in the first line of the CSV. Useful for those spreadsheets that have an excess of empty columns.

ignore trailing empty columns by default

---

xlsx2csv.py

fixed indentation (and typo) on line 601 and repeated flag by removing second '-c'. The command --keepemptycolumns can still be accessed with the full word argument (or a different letter could be chosen). Now runs in Python 2.7.11 and 3.5.1.

fixed indentation on line 601 and repeated flag by removing second '-c'

---

xlsx2csv.py

small change to strip some standard format code stuff. I've only seen 404 and 409 so far.
output:
,May-04,
instead of:
,[$-409]May-04,

ignore "[$-409]" and similar format codes for dates

---

CHANGELOG
setup.py
xlsx2csv.py

My version of excel uses “xl/worksheets/worksheet.xml”.
Also, I frequently have a use for a date field being in its simple
numer form.  So now you can simply use the date format “float”, which
is interpreted as a special case and leaves the field as a number.

Support my version of excel

---

xlsx2csv.py

There was a error if you put an empty option "-p".
```
Traceback (most recent call last):
File "./xlsx2csv.py", line 963, in <module>
elif options.sheetdelimiter[0] == 'x':
IndexError: string index out of range
```

Fix handling of an empty "-p" option.

---

xlsx2csv.py

Note that because there have been changes in every year from 2010 to
now, continuing to express the copyright year as a range is fine.

Update copyright year

---

xlsx2csv.py

Xlsx files generated by WPS or other third parties giving number format error such as  "unknown format None at 58". 
To fix this, we should replace numFmtId to applyNumberFormat.

when numFmtId not found, apply applyNumberFormat

---

xlsx2csv.py

The datetime.time function only accepts integers as its arguments.
On python >= 3 the / operator returns a float data type.
Using the // operator ensures a floor division is used and an int is returned.
(See also [PEP 238 -- Changing the Division Operator](https://www.python.org/dev/peps/pep-0238/))
Fixes the following exception:
```
File "C:\Python34\lib\site-packages\xlsx2csv.py", line 197, in convert
self._convert(sheetid, outfile)
File "C:\Python34\lib\site-packages\xlsx2csv.py", line 277, in _convert
sheet.to_csv(writer)
File "C:\Python34\lib\site-packages\xlsx2csv.py", line 625, in to_csv
self.parser.ParseFile(self.filehandle)
File "..\Modules\pyexpat.c", line 273, in CharacterData
File "C:\Python34\lib\site-packages\xlsx2csv.py", line 687, in handleCharData
d = datetime.time((t / …
```

Use integer divison for format_type time

---

xlsx2csv.py

Move eprint definition before the main script to fix NameError

---

xlsx2csv.py

https://github.com/dilshod/xlsx2csv/commit/8d2ba4e4a618db2df7b88fc8c1f8ddc6b2c0b146#diff-fb3c758f7f6d950554579389ff70a33eL260 forgot to check `sheet_path` exists before trying the other naming options, as a result anything not named `sheet%i` fails:
```
$ unzip -t somefile.xlsx
Archive:  somefile.xlsx
testing: _rels/workbook.xml.rels  OK
testing: _rels/.rels              OK
testing: xl/worksheets/data.xml   OK   <------------
testing: stylesheet.xml           OK
testing: [Content_Types].xml      OK
testing: workbook.xml             OK
alex@aineko:~/src/xlsx2csv$ ./xlsx2csv/xlsx2csv.py -a somefile.xlsx 
-------- 1 - Data
Traceback (most recent call last):
File "./xlsx2csv/xlsx2csv.py", line 1135, in <module>
xlsx2csv.convert(outfile, sheetid)
File "./xlsx2csv/xlsx2csv.py", line 258, in …
```

sheet_path cannot be assumed to exist, need to check with _filehandle

---

xlsx2csv.py

`t="n"` is not currently supported, but with a minor tweak we can by marking such cells as 'float' but only when no style is applied to the cell.

support number fields

---

xlsx2csv.py

When running the tool with a directory as input it required a single output file path, which is redundant for a directory containing multiple input files. 
These changes ensure that either the output can be discarded and then the output will be written to the input directory with each input file ending changed to `.csv` (1), or you can provide an output directory (2).
(1) can be tested by
```
python xlsx2csv.py /path/to/input/dir
```
where the input dir contains some `.xlsx` files, then the converted `.csv` files will be added to the same dir
(2) can be tested by
```
python xlsx2csv.py /path/to/input/dir /path/to/output/dir
```
where the input dir contains some `.xlsx` files, then the converted `.csv` files will be added to the output dir

Handle different outputs when converting from directory

---

xlsx2csv.py

Depending on how your interpreter runs, the `re.match` calls can generate warnings like:
```python
DeprecationWarning: invalid escape sequence '\d'
"""elif re.match("^\d+(\.\d+)?$", self.data) and re.match(".*[hsmdyY]", format_str) and not re.match("""
```
This PR just ensures the calls to `re.match` are also raw string literals (like the calls to `re.sub`).
Thanks!

Update regex string-literals to avoid "DeprecationWarning: invalid escape sequence"

---

xlsx2csv.py

`BadZipfile` (with a small `f`) has been deprecated since Python 3.2, use `BadZipFile` (big `F`) instead, added in 3.2.
* https://docs.python.org/3/library/zipfile.html#zipfile.BadZipfile
* https://github.com/python/cpython/issues/86437

Replace deprecated BadZipfile with BadZipFile

---

xlsx2csv.py

Thank you for the useful utility.
This change prevents the following crash that occurs when invoked with the `--hyperlinks` option:
```
Traceback (most recent call last):
File "./xlsx2csv.py", line 1214, in <module>
main()
File "./xlsx2csv.py", line 1207, in main
xlsx2csv.convert(outfile, sheetid)
File "./xlsx2csv.py", line 234, in convert
self._convert(sheetid, outfile)
File "./xlsx2csv.py", line 352, in _convert
re.sub(r"(<v>[^<>]+)&#13;([^<>]+</v>)", r"\1\\r\2", sheet.filedata)))
File "/usr/lib64/python3.10/re.py", line 209, in sub
return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object
```

hyperlinks crash string bytes

---

xlsx2csv.py

This PR introduces a check for and raises an exception when the user passes a non-existing file as input. Without this PR, when the user passes a non-existing file this error is raised:
> Exception AttributeError: "Xlsx2csv instance has no attribute 'ziphandle'" in <bound method Xlsx2csv.__del__ of <__main__.Xlsx2csv instance at 0x02BD9940>> ignored
This is the same exception raised when a non-XLSX file is passed, making debugging a little confusing. This PR makes the situation clear.

Handle missing input file explicitly

---

README.md
man/xlsx2csv.1.pod
test/run
xlsx2csv.py

Commit 5a14efcef broke input from stdin, with the check added for actually existing files. Add an exception when the file input is "-" so reading from stdin works again. The original commit that introduced this feature did not include documentation. Add documentation to "--help", manpages and the README. Add testing for reading from stdin with python3 so future commits will not break the feature unintentionally.
Fixes: #270

stdin: fix false no file test and add tests for stdin

---

xlsx2csv.py

Fix bug when missing workbook relationship
Add a check to see if the list is empty before trying to access it's
contents. If an excel file has an overridden relationship with no word
"book" in the name it will attempt to grab the first item of an empty
list when looking up workbook relationships.
IndexError: list index out of range
There could be a better fix to this issue I'm not well enough versed in
the xslx specification. The following xlsx file caused the issue.
$ unzip -l some_file.xlsx
Archive:  some_file.xlsx
Length      Date    Time    Name
---------  ---------- -----   ----
142  02-06-2024 13:28   xl/worksheets/_rels/sheet1.xml.rels
65968555  02-06-2024 13:28   xl/worksheets/sheet1.xml
2078037  02-06-2024 13:28   xl/sharedStrings.xml
9867  02-06-2024 13:28   xl/styles.xml
566 …

Fix bug when missing workbook relationship

---

pyproject.toml

Supports python 3.5-3.11 as well.
See also https://github.com/dilshod/xlsx2csv/issues/254

Update pyproject.toml with python support

---

xlsx2csv.py

One of the regexes hadn't been set as a raw string; fixing that can avoid the following error on Python 3.12:
```python
E       and not re.match(".*\[.*[dmhys].*\]", format_str)
E                        ^^^^^^^^^^^^^^^^^^^
E   SyntaxError: invalid escape sequence '\['
```

Fix potential `SyntaxError` when >= Python 3.12 (regex)

---

xlsx2csv.py

I know xlsx2csv doesn't officially support Python 3.13, but there is no reason it couldn't!
We support `xlsx2csv` as an engine in Polars and we'd like to support Python 3.13. Currently, using `xlsx2csv` works fine but it throws a deprecation warning: `re.sub` now expects the `count` parameter as a keyword argument rather than positional.
I checked earlier versions of Python (3.4 onwards and 2.7) and it seems that in all cases, the parameter is named `count`, so using a keyword argument here shouldn't break anything.
It was a simple fix, hopefully this can be a tiny step towards Python 3.13 support!

Fix deprecation warning in `re.sub` for Python 3.13

---

xlsx2csv.py

- Older versions of excel will use \r\n, and the expat xml parser will convert the \r to `_x0008_` which is really messy for the output csv and changes data in ways that upsets users. This forces the string processing to ignore the expat encoding for \r and just replace it with an empty string.

Fix for handling cells with windows-style newline \r\n characters
